# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: filmradar-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filmradar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - filmradar-net

networks:
  filmradar-net:

volumes:
  postgres_data:
